octo:
  shop_id: '%env(OCTO_SHOP_ID)%'
  auto_capture: '%env(OCTO_AUTO_CAPTURE)%'
  notify_url: '%env(OCTO_NOTIFY_URL)%'
  return_url: '%env(OCTO_RETURN_URL)%'
  secret: '%env(OCTO_SHOP_ID)%'
  test: '%env(OCTO_TEST)%'