parameters:
    octo_shop_id: '%env(OCTO_SHOP_ID)%'
    octo_auto_capture: '%env(OCTO_AUTO_CAPTURE)%'
    octo_notify_url: '%env(OCTO_NOTIFY_URL)%'
    octo_secret: '%env(OCTO_SECRET)%'
    octo_test: '%env(OCTO_TEST)%'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Daniil\OctoBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'